
name: Deploy HTML to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare public folder
        run: |
          mkdir -p public/Bayesian_ODE_fermantation
          cp Bayesian_ODE_fermantation/Bayesian_ODE_estim.html public/index.html
          cp -r Bayesian_ODE_fermantation/Bayesian_ODE_estim_files public/Bayesian_ODE_fermantation/
        
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            branch: gh-pages
            folder: ./public
            single-commit: true
